spring:
  datasource:
    name: commerce-lab
    url: jdbc:postgresql://localhost:5432/master_ecom
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080