spring:
  datasource:
    postgres:
      jdbc-url: jdbc:postgresql://${PG_DATABASE_URL}
      username: ${PG_DB_USER}
      password: ${PG_DB_PASS}
      driver-class-name: org.postgresql.Driver
    mysql:
      jdbc-url: jdbc:mysql://${MS_DATABASE_URL}
      username: ${MS_DB_USER}
      password: ${MS_DB_PASS}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      naming:
        # This converts CamelCase to snake_case (OrderItem -> order_item)
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        # This ensures the logical names follow Spring Boot defaults
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 20
        dialect: org.hibernate.dialect.MySQLDialect
        
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  
  security:
    jwt-key: ${JWT_SECRET_KEY}
    remember-key: ${REMEMBER_ME_KEY}
    oauth2:
      client:
        provider:
          google:
            issuer-uri: https://accounts.google.com
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:placeholder}
            client-secret: ${GOOGLE_CLIENT_SECRET:placeholder}
            scope:
              - email
              - profile
  

server:
  port: ${PORT:8080}
  tomcat:
    connection-timeout: 20000