spring:
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:service@gmail.com}
    password: ${MAIL_PASSWORD:NotaPassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:placeholder}
            client-secret: ${GOOGLE_CLIENT_SECRET:placeholder}
            scope:
              - email
              - profile

server:
  port: ${PORT:8080}
  tomcat:
    connection-timeout: 20000