name: Ecommerce Lab QC Suite

on:
  push:
    branches: [ main ]

jobs:
  automation:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: master_ecom_test
          POSTGRES_USERNAME: cloud_user
          POSTGRES_PASSWORD: cloud_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: master_ecom_test
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Make Maven Executable
        run: chmod +x mvnw

      - name: Run Development Tests
        env:
          POSTGRES_USERNAME: cloud_user
          POSTGRES_PASSWORD: cloud_password
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: root_password
        run: ./mvnw test -Dspring.profiles.active=test,postgres